// <auto-generated />
using System;
using DAL.databaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260122023749_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DTO.AccountDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonDTOId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonDTOId");

                    b.HasIndex("PersonId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("DTO.AssignmentDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseDTOId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseDTOId");

                    b.HasIndex("CourseId");

                    b.ToTable("Assignment", (string)null);
                });

            modelBuilder.Entity("DTO.BookDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryDTOId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<int>("TotalDownload")
                        .HasColumnType("int");

                    b.Property<int>("TotalRead")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryDTOId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.ToTable("Book", (string)null);
                });

            modelBuilder.Entity("DTO.BookFileDTO", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int?>("BookDTOId")
                        .HasColumnType("int");

                    b.Property<int?>("FilesDTOId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "FileId");

                    b.HasIndex("BookDTOId");

                    b.HasIndex("FileId");

                    b.HasIndex("FilesDTOId");

                    b.ToTable("Book_File", (string)null);
                });

            modelBuilder.Entity("DTO.CategoryDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("DTO.ClassDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FacultyDTOId")
                        .HasColumnType("int");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TeacherDTOId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyDTOId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TeacherDTOId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("DTO.ClassExamDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ExamId", "ClassId")
                        .IsUnique();

                    b.ToTable("ClassExam", (string)null);
                });

            modelBuilder.Entity("DTO.CourseClassDTO", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("CourseClassDTO");
                });

            modelBuilder.Entity("DTO.CourseDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryDTOId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SemesterDTOId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryDTOId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.HasIndex("SemesterDTOId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("DTO.ExamDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseDTOId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ExamInstruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SemesterDTOId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseDTOId");

                    b.HasIndex("CourseId");

                    b.HasIndex("SemesterDTOId");

                    b.HasIndex("SemesterId");

                    b.ToTable("Exam", (string)null);
                });

            modelBuilder.Entity("DTO.ExamFileDTO", b =>
                {
                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int?>("ExamDTOId")
                        .HasColumnType("int");

                    b.Property<int?>("FilesDTOId")
                        .HasColumnType("int");

                    b.HasKey("ExamId", "FileId");

                    b.HasIndex("ExamDTOId");

                    b.HasIndex("FileId");

                    b.HasIndex("FilesDTOId");

                    b.ToTable("Exam_File", (string)null);
                });

            modelBuilder.Entity("DTO.FacultyDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SchoolDTOId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SchoolDTOId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Faculty", (string)null);
                });

            modelBuilder.Entity("DTO.FilesDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FileSize")
                        .HasColumnType("int");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("DTO.LessonActivityDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LessonPlanDTOId")
                        .HasColumnType("int");

                    b.Property<int>("LessonPlanId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int?>("TimeMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonPlanDTOId");

                    b.HasIndex("LessonPlanId");

                    b.ToTable("LessonActivity", (string)null);
                });

            modelBuilder.Entity("DTO.LessonPlanDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassDTOId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseDTOId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomDTOId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentClassId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassDTOId");

                    b.HasIndex("CourseDTOId");

                    b.HasIndex("CourseId");

                    b.HasIndex("RoomDTOId");

                    b.HasIndex("RoomId");

                    b.HasIndex("StudentClassId");

                    b.ToTable("LessonPlan", (string)null);
                });

            modelBuilder.Entity("DTO.LessonScheduleDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("LessonPlanId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("LessonPlanId");

                    b.HasIndex("RoomId");

                    b.ToTable("LessonSchedule", (string)null);
                });

            modelBuilder.Entity("DTO.PersonDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("DTO.QuestionDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExamDTOId")
                        .HasColumnType("int");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExamDTOId");

                    b.HasIndex("ExamId");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("DTO.QuestionOptionDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int?>("QuestionDTOId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionDTOId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOption", (string)null);
                });

            modelBuilder.Entity("DTO.ResearchTopicDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FacultyDTOId")
                        .HasColumnType("int");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("KeyWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherDTOId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TopicCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyDTOId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("TeacherDTOId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ResearchTopic", (string)null);
                });

            modelBuilder.Entity("DTO.ResearchTopicFileDTO", b =>
                {
                    b.Property<int>("ResearchTopicId")
                        .HasColumnType("int");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int?>("FilesDTOId")
                        .HasColumnType("int");

                    b.Property<int?>("ResearchTopicDTOId")
                        .HasColumnType("int");

                    b.HasKey("ResearchTopicId", "FileId");

                    b.HasIndex("FileId");

                    b.HasIndex("FilesDTOId");

                    b.HasIndex("ResearchTopicDTOId");

                    b.ToTable("ResearchTopic_File", (string)null);
                });

            modelBuilder.Entity("DTO.RoomDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("DTO.SchoolDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("School", (string)null);
                });

            modelBuilder.Entity("DTO.SemesterDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolDTOId")
                        .HasColumnType("int");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolDTOId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Semester", (string)null);
                });

            modelBuilder.Entity("DTO.StudentDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ClassDTOId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("FacultyDTOId")
                        .HasColumnType("int");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonDTOId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassDTOId");

                    b.HasIndex("ClassId");

                    b.HasIndex("FacultyDTOId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("PersonDTOId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("DTO.StudentScoreDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseDTOId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("ScoreType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ScoreValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StudentDTOId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseDTOId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentDTOId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentScore", (string)null);
                });

            modelBuilder.Entity("DTO.SubmissionDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignmentDTOId")
                        .HasColumnType("int");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentDTOId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentDTOId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("StudentDTOId");

                    b.HasIndex("StudentId");

                    b.ToTable("Submission", (string)null);
                });

            modelBuilder.Entity("DTO.SubmissionFileDTO", b =>
                {
                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int?>("FilesDTOId")
                        .HasColumnType("int");

                    b.Property<int?>("SubmissionDTOId")
                        .HasColumnType("int");

                    b.HasKey("SubmissionId", "FileId");

                    b.HasIndex("FileId");

                    b.HasIndex("FilesDTOId");

                    b.HasIndex("SubmissionDTOId");

                    b.ToTable("Submission_File", (string)null);
                });

            modelBuilder.Entity("DTO.TeacherClassDTO", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ClassDTOId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherDTOId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ClassId", "TeacherId");

                    b.HasIndex("ClassDTOId");

                    b.HasIndex("TeacherDTOId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Teacher_Class", (string)null);
                });

            modelBuilder.Entity("DTO.TeacherDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("FacultyDTOId")
                        .HasColumnType("int");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonDTOId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyDTOId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("PersonDTOId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Teacher", (string)null);
                });

            modelBuilder.Entity("DTO.TeacherSchoolDTO", b =>
                {
                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SchoolDTOId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherDTOId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SchoolId", "TeacherId");

                    b.HasIndex("SchoolDTOId");

                    b.HasIndex("TeacherDTOId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Teacher_School", (string)null);
                });

            modelBuilder.Entity("DTO.TeachingScheduleDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassDTOId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseDTOId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomDTOId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("TeacherDTOId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClassDTOId");

                    b.HasIndex("ClassId");

                    b.HasIndex("CourseDTOId");

                    b.HasIndex("CourseId");

                    b.HasIndex("RoomDTOId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TeacherDTOId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeachingSchedule", (string)null);
                });

            modelBuilder.Entity("DTO.TopicObjectiveDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResearchTopicDTOId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResearchTopicDTOId");

                    b.HasIndex("TopicId");

                    b.ToTable("TopicObjective", (string)null);
                });

            modelBuilder.Entity("DTO.TopicProgressDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResearchTopicDTOId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResearchTopicDTOId");

                    b.HasIndex("TopicId");

                    b.ToTable("TopicProgress", (string)null);
                });

            modelBuilder.Entity("DTO.AccountDTO", b =>
                {
                    b.HasOne("DTO.PersonDTO", null)
                        .WithMany("Accounts")
                        .HasForeignKey("PersonDTOId");

                    b.HasOne("DTO.PersonDTO", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DTO.AssignmentDTO", b =>
                {
                    b.HasOne("DTO.CourseDTO", null)
                        .WithMany("Assignments")
                        .HasForeignKey("CourseDTOId");

                    b.HasOne("DTO.CourseDTO", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DTO.BookDTO", b =>
                {
                    b.HasOne("DTO.CategoryDTO", null)
                        .WithMany("Books")
                        .HasForeignKey("CategoryDTOId");

                    b.HasOne("DTO.CategoryDTO", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.PersonDTO", "Person")
                        .WithMany("Books")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DTO.BookFileDTO", b =>
                {
                    b.HasOne("DTO.BookDTO", null)
                        .WithMany("BookFiles")
                        .HasForeignKey("BookDTOId");

                    b.HasOne("DTO.BookDTO", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.FilesDTO", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.FilesDTO", null)
                        .WithMany("BookFiles")
                        .HasForeignKey("FilesDTOId");

                    b.Navigation("Book");

                    b.Navigation("File");
                });

            modelBuilder.Entity("DTO.ClassDTO", b =>
                {
                    b.HasOne("DTO.FacultyDTO", null)
                        .WithMany("Classes")
                        .HasForeignKey("FacultyDTOId");

                    b.HasOne("DTO.FacultyDTO", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.TeacherDTO", null)
                        .WithMany("Classes")
                        .HasForeignKey("TeacherDTOId");

                    b.HasOne("DTO.TeacherDTO", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DTO.ClassExamDTO", b =>
                {
                    b.HasOne("DTO.ClassDTO", "Class")
                        .WithMany("ClassExams")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DTO.ExamDTO", "Exam")
                        .WithMany("ClassExams")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("DTO.CourseClassDTO", b =>
                {
                    b.HasOne("DTO.ClassDTO", "Class")
                        .WithMany("CourseClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DTO.CourseDTO", "Course")
                        .WithMany("CourseClasses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DTO.CourseDTO", b =>
                {
                    b.HasOne("DTO.CategoryDTO", null)
                        .WithMany("Courses")
                        .HasForeignKey("CategoryDTOId");

                    b.HasOne("DTO.CategoryDTO", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.SemesterDTO", null)
                        .WithMany("Courses")
                        .HasForeignKey("SemesterDTOId");

                    b.HasOne("DTO.SemesterDTO", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("DTO.ExamDTO", b =>
                {
                    b.HasOne("DTO.CourseDTO", null)
                        .WithMany("Exams")
                        .HasForeignKey("CourseDTOId");

                    b.HasOne("DTO.CourseDTO", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.SemesterDTO", null)
                        .WithMany("Exams")
                        .HasForeignKey("SemesterDTOId");

                    b.HasOne("DTO.SemesterDTO", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("DTO.ExamFileDTO", b =>
                {
                    b.HasOne("DTO.ExamDTO", null)
                        .WithMany("ExamFiles")
                        .HasForeignKey("ExamDTOId");

                    b.HasOne("DTO.ExamDTO", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.FilesDTO", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.FilesDTO", null)
                        .WithMany("ExamFiles")
                        .HasForeignKey("FilesDTOId");

                    b.Navigation("Exam");

                    b.Navigation("File");
                });

            modelBuilder.Entity("DTO.FacultyDTO", b =>
                {
                    b.HasOne("DTO.SchoolDTO", null)
                        .WithMany("Faculties")
                        .HasForeignKey("SchoolDTOId");

                    b.HasOne("DTO.SchoolDTO", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("DTO.LessonActivityDTO", b =>
                {
                    b.HasOne("DTO.LessonPlanDTO", null)
                        .WithMany("LessonActivities")
                        .HasForeignKey("LessonPlanDTOId");

                    b.HasOne("DTO.LessonPlanDTO", "LessonPlan")
                        .WithMany()
                        .HasForeignKey("LessonPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LessonPlan");
                });

            modelBuilder.Entity("DTO.LessonPlanDTO", b =>
                {
                    b.HasOne("DTO.ClassDTO", null)
                        .WithMany("LessonPlans")
                        .HasForeignKey("ClassDTOId");

                    b.HasOne("DTO.CourseDTO", null)
                        .WithMany("LessonPlans")
                        .HasForeignKey("CourseDTOId");

                    b.HasOne("DTO.CourseDTO", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.RoomDTO", null)
                        .WithMany("LessonPlans")
                        .HasForeignKey("RoomDTOId");

                    b.HasOne("DTO.RoomDTO", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.ClassDTO", "Class")
                        .WithMany()
                        .HasForeignKey("StudentClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Course");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DTO.LessonScheduleDTO", b =>
                {
                    b.HasOne("DTO.ClassDTO", "Class")
                        .WithMany("LessonSchedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.LessonPlanDTO", "LessonPlan")
                        .WithMany("LessonSchedules")
                        .HasForeignKey("LessonPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DTO.RoomDTO", "Room")
                        .WithMany("LessonSchedules")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("LessonPlan");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DTO.QuestionDTO", b =>
                {
                    b.HasOne("DTO.ExamDTO", null)
                        .WithMany("Questions")
                        .HasForeignKey("ExamDTOId");

                    b.HasOne("DTO.ExamDTO", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("DTO.QuestionOptionDTO", b =>
                {
                    b.HasOne("DTO.QuestionDTO", null)
                        .WithMany("QuestionOptions")
                        .HasForeignKey("QuestionDTOId");

                    b.HasOne("DTO.QuestionDTO", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DTO.ResearchTopicDTO", b =>
                {
                    b.HasOne("DTO.FacultyDTO", null)
                        .WithMany("ResearchTopics")
                        .HasForeignKey("FacultyDTOId");

                    b.HasOne("DTO.FacultyDTO", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.TeacherDTO", null)
                        .WithMany("ResearchTopics")
                        .HasForeignKey("TeacherDTOId");

                    b.HasOne("DTO.TeacherDTO", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DTO.ResearchTopicFileDTO", b =>
                {
                    b.HasOne("DTO.FilesDTO", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.FilesDTO", null)
                        .WithMany("ResearchTopicFiles")
                        .HasForeignKey("FilesDTOId");

                    b.HasOne("DTO.ResearchTopicDTO", null)
                        .WithMany("ResearchTopicFiles")
                        .HasForeignKey("ResearchTopicDTOId");

                    b.HasOne("DTO.ResearchTopicDTO", "ResearchTopic")
                        .WithMany()
                        .HasForeignKey("ResearchTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("ResearchTopic");
                });

            modelBuilder.Entity("DTO.SemesterDTO", b =>
                {
                    b.HasOne("DTO.SchoolDTO", null)
                        .WithMany("Semesters")
                        .HasForeignKey("SchoolDTOId");

                    b.HasOne("DTO.SchoolDTO", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("School");
                });

            modelBuilder.Entity("DTO.StudentDTO", b =>
                {
                    b.HasOne("DTO.ClassDTO", null)
                        .WithMany("Students")
                        .HasForeignKey("ClassDTOId");

                    b.HasOne("DTO.ClassDTO", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.FacultyDTO", null)
                        .WithMany("Students")
                        .HasForeignKey("FacultyDTOId");

                    b.HasOne("DTO.FacultyDTO", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.PersonDTO", null)
                        .WithMany("Students")
                        .HasForeignKey("PersonDTOId");

                    b.HasOne("DTO.PersonDTO", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Faculty");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DTO.StudentScoreDTO", b =>
                {
                    b.HasOne("DTO.CourseDTO", null)
                        .WithMany("StudentScores")
                        .HasForeignKey("CourseDTOId");

                    b.HasOne("DTO.CourseDTO", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.StudentDTO", null)
                        .WithMany("StudentScores")
                        .HasForeignKey("StudentDTOId");

                    b.HasOne("DTO.StudentDTO", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DTO.SubmissionDTO", b =>
                {
                    b.HasOne("DTO.AssignmentDTO", null)
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentDTOId");

                    b.HasOne("DTO.AssignmentDTO", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.StudentDTO", null)
                        .WithMany("Submissions")
                        .HasForeignKey("StudentDTOId");

                    b.HasOne("DTO.StudentDTO", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DTO.SubmissionFileDTO", b =>
                {
                    b.HasOne("DTO.FilesDTO", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.FilesDTO", null)
                        .WithMany("SubmissionFiles")
                        .HasForeignKey("FilesDTOId");

                    b.HasOne("DTO.SubmissionDTO", null)
                        .WithMany("SubmissionFiles")
                        .HasForeignKey("SubmissionDTOId");

                    b.HasOne("DTO.SubmissionDTO", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("DTO.TeacherClassDTO", b =>
                {
                    b.HasOne("DTO.ClassDTO", null)
                        .WithMany("TeacherClasses")
                        .HasForeignKey("ClassDTOId");

                    b.HasOne("DTO.ClassDTO", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.TeacherDTO", null)
                        .WithMany("TeacherClasses")
                        .HasForeignKey("TeacherDTOId");

                    b.HasOne("DTO.TeacherDTO", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DTO.TeacherDTO", b =>
                {
                    b.HasOne("DTO.FacultyDTO", null)
                        .WithMany("Teachers")
                        .HasForeignKey("FacultyDTOId");

                    b.HasOne("DTO.FacultyDTO", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.PersonDTO", null)
                        .WithMany("Teachers")
                        .HasForeignKey("PersonDTOId");

                    b.HasOne("DTO.PersonDTO", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DTO.TeacherSchoolDTO", b =>
                {
                    b.HasOne("DTO.SchoolDTO", null)
                        .WithMany("TeacherSchools")
                        .HasForeignKey("SchoolDTOId");

                    b.HasOne("DTO.SchoolDTO", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.TeacherDTO", null)
                        .WithMany("TeacherSchools")
                        .HasForeignKey("TeacherDTOId");

                    b.HasOne("DTO.TeacherDTO", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DTO.TeachingScheduleDTO", b =>
                {
                    b.HasOne("DTO.ClassDTO", null)
                        .WithMany("TeachingSchedules")
                        .HasForeignKey("ClassDTOId");

                    b.HasOne("DTO.ClassDTO", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DTO.CourseDTO", null)
                        .WithMany("TeachingSchedules")
                        .HasForeignKey("CourseDTOId");

                    b.HasOne("DTO.CourseDTO", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DTO.RoomDTO", null)
                        .WithMany("TeachingSchedules")
                        .HasForeignKey("RoomDTOId");

                    b.HasOne("DTO.RoomDTO", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DTO.TeacherDTO", null)
                        .WithMany("TeachingSchedules")
                        .HasForeignKey("TeacherDTOId");

                    b.HasOne("DTO.TeacherDTO", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Course");

                    b.Navigation("Room");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DTO.TopicObjectiveDTO", b =>
                {
                    b.HasOne("DTO.ResearchTopicDTO", null)
                        .WithMany("TopicObjectives")
                        .HasForeignKey("ResearchTopicDTOId");

                    b.HasOne("DTO.ResearchTopicDTO", "ResearchTopic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResearchTopic");
                });

            modelBuilder.Entity("DTO.TopicProgressDTO", b =>
                {
                    b.HasOne("DTO.ResearchTopicDTO", null)
                        .WithMany("TopicProgresses")
                        .HasForeignKey("ResearchTopicDTOId");

                    b.HasOne("DTO.ResearchTopicDTO", "ResearchTopic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResearchTopic");
                });

            modelBuilder.Entity("DTO.AssignmentDTO", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("DTO.BookDTO", b =>
                {
                    b.Navigation("BookFiles");
                });

            modelBuilder.Entity("DTO.CategoryDTO", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("DTO.ClassDTO", b =>
                {
                    b.Navigation("ClassExams");

                    b.Navigation("CourseClasses");

                    b.Navigation("LessonPlans");

                    b.Navigation("LessonSchedules");

                    b.Navigation("Students");

                    b.Navigation("TeacherClasses");

                    b.Navigation("TeachingSchedules");
                });

            modelBuilder.Entity("DTO.CourseDTO", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("CourseClasses");

                    b.Navigation("Exams");

                    b.Navigation("LessonPlans");

                    b.Navigation("StudentScores");

                    b.Navigation("TeachingSchedules");
                });

            modelBuilder.Entity("DTO.ExamDTO", b =>
                {
                    b.Navigation("ClassExams");

                    b.Navigation("ExamFiles");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("DTO.FacultyDTO", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("ResearchTopics");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("DTO.FilesDTO", b =>
                {
                    b.Navigation("BookFiles");

                    b.Navigation("ExamFiles");

                    b.Navigation("ResearchTopicFiles");

                    b.Navigation("SubmissionFiles");
                });

            modelBuilder.Entity("DTO.LessonPlanDTO", b =>
                {
                    b.Navigation("LessonActivities");

                    b.Navigation("LessonSchedules");
                });

            modelBuilder.Entity("DTO.PersonDTO", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Books");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("DTO.QuestionDTO", b =>
                {
                    b.Navigation("QuestionOptions");
                });

            modelBuilder.Entity("DTO.ResearchTopicDTO", b =>
                {
                    b.Navigation("ResearchTopicFiles");

                    b.Navigation("TopicObjectives");

                    b.Navigation("TopicProgresses");
                });

            modelBuilder.Entity("DTO.RoomDTO", b =>
                {
                    b.Navigation("LessonPlans");

                    b.Navigation("LessonSchedules");

                    b.Navigation("TeachingSchedules");
                });

            modelBuilder.Entity("DTO.SchoolDTO", b =>
                {
                    b.Navigation("Faculties");

                    b.Navigation("Semesters");

                    b.Navigation("TeacherSchools");
                });

            modelBuilder.Entity("DTO.SemesterDTO", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("DTO.StudentDTO", b =>
                {
                    b.Navigation("StudentScores");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("DTO.SubmissionDTO", b =>
                {
                    b.Navigation("SubmissionFiles");
                });

            modelBuilder.Entity("DTO.TeacherDTO", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("ResearchTopics");

                    b.Navigation("TeacherClasses");

                    b.Navigation("TeacherSchools");

                    b.Navigation("TeachingSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
